### PR TITLE
Added optional backgroundColor and textStyle to bakeToast

### PR DESCRIPTION
**Pull request by toniremi**
I added backgroundColor and textStyle as optional to the bakeToast. This way the user can override the background color and text styles shown for the toast for all toast types. If the user does not provide a backgroundColor or textStyle then I default to the backgroundColor and textStyles used for each different type of toast. But this way users have more flexibility and can also use normal type with background color as their error toast if they do not want to display icons.

### CODE REVIEW

**Comment by toniremi** [comment]
Pull request for commit to add backgroundColor and textStyle as optional to the bakeToast

**Comment by fayaz07** [comment]
Thanks @toniremi

**Review by fayaz07 — APPROVED** [review]

**Comment by fayaz07** [comment]
@toniremi Can you please add a commit to resolve the lint errors?

**Comment by toniremi** [comment]
Ah yeah sorry about that. Let me review it and fix it and then I'll send it again.

**Comment by toniremi** [comment]
I will close this pull request and open a new one with this changes plus fixes for lint

**Pull request closed without merging**
