### PR TITLE
Updated connectivity package, added toast docs

### PR DESCRIPTION
**Pull request by pranathireddyk**

### CODE REVIEW

**Comment by pranathireddyk** [comment]
Fixes #27 #28

**Comment by fayaz07** [comment]
Please remove `FlatButton` and replace it with alternative

**Review by fayaz07 — APPROVED** [review]

**Comment by fayaz07** [comment]
@all-contributors please add @pranathireddyk  for code

**Comment by fayaz07** [comment]
Thank you @all-contributors bot

**Pull request merged**
